FROM node:18.12.1-alpine3.17

WORKDIR /app

ENV NODE_ENV production

COPY package.json yarn.lock .

RUN yarn

COPY . .

RUN npx prisma generate client && yarn build

RUN mkdir /run/secrets && touch /run/secrets/postgres_password && \
  chown -R node:node /app /run/secrets/postgres_password

USER node

CMD ["yarn", "start:prod"]